output_dir: /home/jianl/automation/MovieMaker/output
sucai_dir: /home/jianl/automation/react/moviemakerui/public/admin
system_font_dir: /usr/share/fonts/truetype/
font: fonts/XiaoKeNaiLaoTi/XiaoKeNaiLaoTiShangYongMianFei@QingKeZiTi-2.ttf
video_format: .mp4